# Basic info
title: SeriousSirius
email:
description:

# URL options
baseurl: ""
url: ""

# Collections settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
  media:
    output: false

# Defaults settings
defaults:
  -
    scope:
      path: ""
      type: projects
    values:
      layout: "project"
      css: /css/project.min.css
  -
    scope:
      path: ""
      type: categories
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
      css: /css/post.min.css
      permalink: /:categories/:title

exclude: [".gitignore"]

# Build settings
markdown: kramdown