title: SeriousSirius
email:
description:

baseurl: ""
url: ""

collections:
  projects:
    output: true
    permalink: /:collection/:path/

twitter_username: jekyllrb
github_username: serioussirius

markdown: kramdown

# theme: minima