# Basic info
title: SeriousSirius
email:
description:

# URL options
baseurl: ""
url: ""

# Collections settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
  social-media:
    output: false

# Defaults settings
defaults:
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
      css: /css/project.min.css


exclude: [".gitignore"]

# Social network links
github_username: serioussirius

# Build settings
markdown: kramdown

# Custom theme
# theme: minima