# Basic info
title: SeriousSirius
email:
description:

# URL options
baseurl: "https://serioussirius.github.io/"
url: "/"

# Collections settings
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  

exclude: [".gitignore"]

# Social network links
github_username: serioussirius

# Build settings
markdown: kramdown

# Custom theme
# theme: minima